fixes ci for metaphor-frontend publish through release

diff --git a/civo-github/mgmt-cluster-template/components/argo-workflows/cwfts/cwft-git.yaml b/civo-github/mgmt-cluster-template/components/argo-workflows/cwfts/cwft-git.yaml
--- a/civo-github/mgmt-cluster-template/components/argo-workflows/cwfts/cwft-git.yaml
+++ b/civo-github/mgmt-cluster-template/components/argo-workflows/cwfts/cwft-git.yaml
@@ -10,99 +10,16 @@ spec:
     inputs:
       parameters:
       - name: appName
-        value: "{{workflow.parameters.appName}}"
-      - name: appRepoUrl
-        value: "{{workflow.parameters.gitServerUrl}}/{{workflow.parameters.gitOwner}}/{{workflow.parameters.appName}}"
-      - name: gitopsRepoUrl
-        value: "{{workflow.parameters.gitServerUrl}}/{{workflow.parameters.gitOwner}}/gitops"
       - name: branch
-        value: "{{workflow.parameters.branch}}"
+        default: main
+      - name: gitUrlNoProtocol
       artifacts:
-      - name: app-source
+      - name: repo-source
         path: "/src/{{inputs.parameters.appName}}"
         git:
-          repo: "{{inputs.parameters.appRepoUrl}}"
+          repo: "{{inputs.parameters.gitUrlNoProtocol}}/{{inputs.parameters.appName}}.git"
           branch: "{{inputs.parameters.branch}}"
           singleBranch: true
-          usernameSecret:
-            name: ci-secrets
-            key: username
-          passwordSecret:
-            name: ci-secrets
-            key: password
-      - name: gitops-source
-        path: /src/gitops
-        git:
-          repo: "{{inputs.parameters.gitopsRepoUrl}}"
-          branch: main
-          singleBranch: true
-          usernameSecret:
-            name: ci-secrets
-            key: username
-          passwordSecret:
-            name: ci-secrets
-            key: password
-    container:
-      image: golang:latest
-      command: ["sh", "-c"]
-      workingDir: /src
-      args:
-      - ls -la {{inputs.parameters.appName}};
-        ls -la gitops;
-    outputs:
-      artifacts:
-      - name: repo-source
-        path: /src
-  - name: pull-commit-push
-    retryStrategy:
-      limit: "5"
-    inputs:
-      artifacts:
-      - name: repo-source
-        path: /src
-      parameters:
-      - name: repoName
-      - name: commitMessage
-      - name: gitOwner
-        value: "{{workflow.parameters.gitOwner}}"
-    container:
-      image: golang:latest
-      command: ["sh", "-c"]
-      workingDir: "/src/{{inputs.parameters.repoName}}"
-      envFrom:
-      - secretRef:
-          name: ci-secrets
-      # todo review last two git commands
-      args:
-      - git remote set-url origin https://${username}:${password}@github.com/{{inputs.parameters.gitOwner}}/{{inputs.parameters.repoName}}.git >/dev/null 2>&1;
-        git remote -v;
-        git config --global user.email 'k-ray@example.com';
-        git config --global user.name 'kuebfirst-bot';
-        git status;
-        git pull --ff-only;
-        git add .;
-        git commit -m "{{inputs.parameters.commitMessage}}" || echo "Assuming this was committed on previous run, not erroring out";
-        git push || bash -c "sleep 10 && echo 'waiting before trying again' && exit 1";
-  - name: git-checkout-with-gitops-ssh
-    inputs:
-      parameters:
-      - name: appDir
-      - name: branch
-        value: "{{workflow.parameters.branch}}"
-        default: main
-      - name: buildImage
-        value: "{{workflow.parameters.buildImage}}"
-        default: kubefirst/ci-tools:39e6cb
-      - name: gitopsRepoUrl
-        value: "{{workflow.parameters.gitopsRepoUrl}}"
-        default: "ssh://<GITOPS_REPO_GIT_URL>"
-      - name: gitRepoUrl
-      artifacts:
-      - name: repo-source
-        path: "{{inputs.parameters.appDir}}"
-        git:
-          repo: "{{inputs.parameters.gitRepoUrl}}"
-          revision: "{{inputs.parameters.branch}}"
           insecureIgnoreHostKey: true
           sshPrivateKeySecret:
             name: ci-secrets
@@ -110,8 +27,9 @@ spec:
       - name: gitops-source
         path: /src/gitops
         git:
-          repo: "ssh://<GITOPS_REPO_GIT_URL>"
-          revision: "main"
+          repo: "{{inputs.parameters.gitUrlNoProtocol}}/gitops.git"
+          branch: "main"
+          singleBranch: true
           insecureIgnoreHostKey: true
           sshPrivateKeySecret:
             name: ci-secrets
@@ -121,8 +39,59 @@ spec:
       command: ["/bin/sh", "-c"]
       args:
       - ls -la /src &&
-        ls -la {{inputs.parameters.appDir}}
+        ls -la /src/{{inputs.parameters.appName}}
     outputs:
       artifacts:
       - name: repo-source
         path: /src
+  - name: pull-commit-push
+    retryStrategy:
+      limit: "5"
+    # todo get ssh item not all secrets
+    volumes:
+     - name: ssh-key
+       secret:
+          defaultMode: 256
+          secretName: ci-secrets
+    inputs:
+      artifacts:
+      - name: repo-source
+        path: /src
+      parameters:
+        - name: commitMessage
+        - name: gitUrlNoProtocol
+        - name: repoName
+    container:
+      workingDir: "/src/{{inputs.parameters.repoName}}"
+      image: golang:latest
+      command: ["/bin/sh", "-c"]
+      volumeMounts:
+      - mountPath: "/mnt/secrets"
+        name: ssh-key
+        readOnly: true
+      args:
+      - set -e;
+
+        eval `ssh-agent -s`;
+        mkdir $HOME/.ssh;
+        cat /mnt/secrets/SSH_PRIVATE_KEY > $HOME/.ssh/id_ed25519;
+        echo -n "\\n" >> $HOME/.ssh/id_ed25519;
+        chmod 0600 $HOME/.ssh/id_ed25519;
+        ssh-add $HOME/.ssh/id_ed25519;
+
+        echo "Host *" >> $HOME/.ssh/config;
+        echo "  StrictHostKeyChecking no" >> $HOME/.ssh/config;
+        echo "  User git" >> $HOME/.ssh/config;
+        echo "  IdentitiesOnly yes" >> $HOME/.ssh/config;
+        echo "  UserKnownHostsFile /dev/null" >> $HOME/.ssh/config;
+        chmod 0700 $HOME/.ssh/config;
+        
+        git config --global user.email 'jared@kubeshop.io';
+        git config --global user.name 'kubefirst-bot';
+        git remote set-url origin '{{inputs.parameters.gitUrlNoProtocol}}/{{inputs.parameters.repoName}}.git';
+        git remote -v;
+        git status;
+        git pull;
+        git add .;
+        git commit -m "{{inputs.parameters.commitMessage}}"  || echo "Assuming this was committed on previous run, not erroring out" ;
+        git push;
