Civo domain refactor (#259)
* initial content for civo github

* update all tokens for civo

* remove gitlab assets

* backend config adjustment

* tokenize cluster name

* fix missed tokens

* remove backend until we get to cluster complete

* forgot to add output for repo name

* adjust github repo module

* adjust github repo module

* fix output name

* fix output name

* output fix for civo

* add external-dns, cert-manager, and ingress-nginx

* update console version and add ingress details minus auth

* fix output path of kubeconfig

* token adjustments, missing aws envs

* fix templates remove creds, add secrets

* remove access key references

* holding off on pre-publish of ci

* adds chartmuseum secret, fixes email token, adds storage for vault

* adds vault ingress

* fix vault ingress spec

* get latest external-dns image for chart

* fix ingress spelling

* adds adjustments for atlantis ingress

* adopt ingress class name vs annotation

* add chartmuseum secrets from vault

* adds chartmuseum ingress

* adds secret and argo update for object storage

* adds argo workflows ingress and secret for object store connectivity

* remove minio and extra metaphors

* argo workflows sso add service accounts for roles

* remove gitlab folder from github install

* adjustments for private key to get into vault and use

* adjusts commit ssh template for civo ci

* revert chart version for external-dns

* fix sync interval for external secrets

* adopt staging certificate issuer

* remove external secrets to find issues

* refactor for inintial mgmt cluster

* adopt new folder structure

* adjust path for registrations

* add cluster name to path

* rename registry file and add workload cluster tempalte

* hated the -components variation

* formatting changes

* fix mgmt cluster registration

* add clustername to registry

* fix registry name to remove cluster identifier

* remove external secrets to find issues

* sync wave update, file rename, update refs

* sync wave update, file rename, update refs

* refactor eso secret store

* fix artifact bucket connection

* add clusterName

diff --git a/components/argo-cwfts/cwft-git.yaml b/components/argo-cwfts/cwft-git.yaml
--- a/components/argo-cwfts/cwft-git.yaml
+++ b/components/argo-cwfts/cwft-git.yaml
@@ -6,7 +6,7 @@ spec:
   templates:
   - name: git-checkout-with-gitops-ssh
     inputs:
-      parameters: 
+      parameters:
       - name: appDir
       - name: branch
         value: "{{workflow.parameters.branch}}"
@@ -16,7 +16,7 @@ spec:
         default: kubefirst/ci-tools:39e6cb
       - name: gitopsRepoUrl
         value: "{{workflow.parameters.gitopsRepoUrl}}"
-        default: "ssh://<FULL_REPO_GITOPS_URL>"
+        default: "ssh://git@github.com/your-dns-io/gitops.git"
       - name: gitRepoUrl
       artifacts:
       - name: repo-source
@@ -27,31 +27,30 @@ spec:
           insecureIgnoreHostKey: true
           sshPrivateKeySecret:
             name: ci-secrets
-            key: SSH_PRIVATE_KEY    
+            key: SSH_PRIVATE_KEY
       - name: gitops-source
         path: /src/gitops
         git:
-          repo: "ssh://<FULL_REPO_GITOPS_URL_SSH>"
+          repo: "ssh://git@github.com/your-dns-io/gitops.git"
           revision: "main"
           insecureIgnoreHostKey: true
           sshPrivateKeySecret:
             name: ci-secrets
-            key: SSH_PRIVATE_KEY    
-            
+            key: SSH_PRIVATE_KEY
     container:
       image: golang:latest
       command: ["/bin/sh", "-c"]
-      args: 
-      - ls -la /src && 
+      args:
+      - ls -la /src &&
         ls -la {{inputs.parameters.appDir}}
     outputs:
       artifacts:
       - name: repo-source
-        path: /src  
-        
+        path: /src
+
   - name: git-checkout-with-gitops
     inputs:
-      parameters: 
+      parameters:
       - name: appDir
       - name: branch
         value: "{{workflow.parameters.branch}}"
@@ -89,8 +88,8 @@ spec:
     container:
       image: golang:latest
       command: ["/bin/sh", "-c"]
-      args: 
-      - ls -la /src && 
+      args:
+      - ls -la /src &&
         ls -la {{inputs.parameters.appDir}}
     outputs:
       artifacts:
@@ -99,12 +98,12 @@ spec:
 
   - name: git-commit
     retryStrategy:
-      limit: "5"    
+      limit: "5"
     inputs:
       artifacts:
       - name: repo-source
         path: /src
-      parameters: 
+      parameters:
         - name: appDir
         - name: commitMessage
         - name: repoPath
@@ -121,7 +120,7 @@ spec:
       image: golang:latest
       command: ["/bin/sh", "-c"]
       # todo is this remote set-url good enough?
-      args: 
+      args:
         - git remote set-url origin https://$USERNAME:$PERSONAL_ACCESS_TOKEN@{{inputs.parameters.repoPath}} 2>/dev/null;
           git remote -v;
           git config --global user.email '{{inputs.parameters.gitUserEmail}}';
@@ -137,7 +136,8 @@ spec:
 
   - name: git-commit-ssh
     retryStrategy:
-      limit: "5"      
+      limit: "5"
+    # todo get ssh item not all secrets
     volumes:
      - name: ssh-key
        secret:
@@ -147,61 +147,62 @@ spec:
       artifacts:
       - name: repo-source
         path: /src
-      parameters: 
-        - name: appDir
+      parameters:
+        - name: repoName
+          value: "{{workflow.parameters.repoName}}"
         - name: commitMessage
-        - name: repoPath
-          value: "{{workflow.parameters.repoPath}}"
-          default: ssh://<FULL_REPO_GITOPS_URL_SSH>
+        - name: repositoryGitURL
+          value: "{{workflow.parameters.repositoryGitURL}}"
         - name: gitUserEmail
           value: "{{workflow.parameters.gitUserEmail}}"
-          default: <EMAIL_ADDRESS>
+          default: jared@kubeshop.io
         - name: gitUsername
           value: "{{workflow.parameters.gitUsername}}"
           default: gitlab-bot
     container:
-      workingDir: "{{inputs.parameters.appDir}}"
+      workingDir: "/src/{{inputs.parameters.repoName}}"
       image: golang:latest
       command: ["/bin/sh", "-c"]
-      # todo is this remote set-url good enough?   
+      # todo is this remote set-url good enough?
       volumeMounts:
-        - mountPath: "/mnt/secrets"
-          name: ssh-key
-          readOnly: true         
-      args: 
-        - ls -la /mnt/secrets;
-          mkdir $HOME/.ssh;
-          ls -la  $HOME/.ssh/;
-          echo "Host *" >> $HOME/.ssh/config;
-          echo "  IdentityFile  /mnt/secrets/SSH_PRIVATE_KEY" >> $HOME/.ssh/config;
-          echo "  StrictHostKeyChecking no" >> $HOME/.ssh/config;
-          echo "  User git" >> $HOME/.ssh/config;
-          echo "  IdentitiesOnly yes" >> $HOME/.ssh/config;          
-          echo "  UserKnownHostsFile /dev/null" >> $HOME/.ssh/config;  
-          cat $HOME/.ssh/config;     
-          git remote set-url origin {{inputs.parameters.repoPath}} 2>/dev/null;
-          git remote -v;
-          git config --global user.email '{{inputs.parameters.gitUserEmail}}';
-          git config --global user.name '{{inputs.parameters.gitUsername}}';
-          git status;
-          git pull;
-          git add .;
-          git commit -m "{{inputs.parameters.commitMessage}}"  || echo "Assuming this was committed on previous run, not erroring out" ;
-          git push || bash -c "sleep 10 && echo 'waiting before trying again' && exit 1";
+      - mountPath: "/mnt/secrets"
+        name: ssh-key
+        readOnly: true
+      args:
+      - set -e;
 
-      envFrom:
-      - secretRef:
-          name: ci-secrets
+        eval `ssh-agent -s`;
+        mkdir $HOME/.ssh;
+        cat /mnt/secrets/SSH_PRIVATE_KEY > $HOME/.ssh/id_ed25519;
+        echo -n "\\n" >> $HOME/.ssh/id_ed25519;
+        chmod 0600 $HOME/.ssh/id_ed25519;
+        ssh-add $HOME/.ssh/id_ed25519;
 
-          
-          
+        echo "Host *" >> $HOME/.ssh/config;
+        echo "  StrictHostKeyChecking no" >> $HOME/.ssh/config;
+        echo "  User git" >> $HOME/.ssh/config;
+        echo "  IdentitiesOnly yes" >> $HOME/.ssh/config;
+        echo "  UserKnownHostsFile /dev/null" >> $HOME/.ssh/config;
+        chmod 0700 $HOME/.ssh/config;
+        
+        git config --global user.email '{{inputs.parameters.gitUserEmail}}';
+        git config --global user.name '{{inputs.parameters.gitUsername}}';
+        git remote set-url origin '{{inputs.parameters.repositoryGitURL}}';
+        git remote -v;
+        git status;
+        git pull;
+        git add .;
+        git commit -m "{{inputs.parameters.commitMessage}}"  || echo "Assuming this was committed on previous run, not erroring out" ;
+        git push || bash -c "sleep 10 && echo 'waiting before trying again' && exit 1";
+
+
 
   - name: git-short-sha
     inputs:
       artifacts:
       - name: repo-source
         path: /src
-      parameters: 
+      parameters:
       - name: appDir
     script:
       image: golang:latest
